import type { Report } from "@/lib/schema";

/** Quote a font-family name only when it needs it (contains whitespace). */
function cssFontName(name: string): string {
  return /\s/.test(name) ? `"${name}"` : name;
}

/**
 * Derived view: generate a Tailwind v4 `@theme` CSS file from the report.
 * Traces 1:1 to frontmatter fields with zero schema changes or invented values.
 *
 * Placed in its own module (DIST-071) so client callers (`app/page.tsx`) do not
 * pull `js-yaml` or `reportSchema` into the browser bundle.
 */
export function emitTailwindTheme(report: Report): string {
  const lines: string[] = [
    `/* Generated by Distill from ${report.source.ref} (captured ${report.source.capturedAt}). */`,
    "@theme {",
  ];

  for (const c of report.palette.colors) {
    if (c.role) {
      lines.push(`  --color-${c.role}: ${c.hex};`);
    }
  }

  if (report.typography) {
    const seenRoles = new Set<string>();
    for (const f of report.typography.families) {
      if (!seenRoles.has(f.role)) {
        seenRoles.add(f.role);
        const stack = f.stack.length > 0 ? f.stack : [f.name];
        lines.push(`  --font-${f.role}: ${stack.map(cssFontName).join(", ")};`);
      }
    }
    for (const s of report.typography.scale) {
      lines.push(`  --text-${s.token}: ${s.sizePx}px;`);
      lines.push(`  --text-${s.token}--line-height: ${s.lineHeight};`);
      lines.push(`  --text-${s.token}--font-weight: ${s.weight};`);
      lines.push(`  --text-${s.token}--letter-spacing: ${s.letterSpacing};`);
    }
  }

  if (report.spacing) {
    lines.push(`  --spacing: ${report.spacing.baseUnitPx}px;`);
  }

  if (report.radius) {
    report.radius.scale.forEach((r, i) => {
      lines.push(`  --radius-${i + 1}: ${r};`);
    });
  }

  if (report.elevation && report.elevation.shadows.length > 0) {
    for (const s of report.elevation.shadows) {
      lines.push(`  --shadow-${s.name}: ${s.value};`);
    }
  }

  lines.push("}");

  if (report.paletteDark && report.paletteDark.colors.length > 0) {
    lines.push("", "@media (prefers-color-scheme: dark) {", "  :root {");
    for (const c of report.paletteDark.colors) {
      if (c.role) {
        lines.push(`    --color-${c.role}: ${c.hex};`);
      }
    }
    lines.push("  }", "}");
  }

  return lines.join("\n") + "\n";
}
